//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chatter3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat
    {
        public int ChatId { get; set; }
        public string UserId { get; set; }
        public string ChatMessage { get; set; }
        public System.DateTime DateTimeStamp { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
